<Project Sdk="Aspire.AppHost.Sdk/13.4.5">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UserSecretsId>e76a321b-d55e-4fd0-8d46-553fdc3be4da</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Keycloak" Version="13.4.5-preview.1.26316.12" />
        <ProjectReference Include="..\KeyCloak.Aspire.Extensions\KeyCloak.Aspire.Extensions.csproj" IsAspireProjectResource="false"/>
    </ItemGroup>

</Project>
