name: Publish NuGet Package

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4
            -   name: Setup .NET
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '10.0.x'
            -   name: Restore Dependencies
                run: dotnet restore
            -   name: Build Project
                run: dotnet build --configuration Release --no-restore
            -   name: Verify commit exists in origin/main
                run: |
                    git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
                    git branch --remote --contains | grep origin/main          
            -   name: Set VERSION variable from tag
                run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            -   name: Build
                run: dotnet build --configuration Release /p:Version=${VERSION}
            -   name: Pack
                run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output nupkg/
            -   name: Push to NuGet
                run: dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
